
CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL DEFAULT "user",
    Token VARCHAR(512),
    token_expires_at TIMESTAMP,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE EVENT IF NOT EXISTS delete_expired_tokens
ON SCHEDULE EVERY 1 HOUR
DO
DELETE FROM Users WHERE token_expires_at < NOW();


